openapi: 3.1.0
info:
  title: EverNet VMM API
  version: 1.0.0
  description: Core VMM APIs for orchestrator, reporting, scheduler and dashboard.
servers:
  - url: http://localhost:3011
paths:
  /healthz:
    get:
      summary: Generic health check endpoint
      x-access-class: Ops
      responses:
        "200":
          description: Service health
  /metrics:
    get:
      summary: Prometheus metrics endpoint
      x-access-class: Ops
      responses:
        "200":
          description: Metrics payload
  /internal/events:
    post:
      summary: Ingest AI event from worker
      x-access-class: Internal
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AiEvent"
      responses:
        "200":
          description: Accepted
  /api/v1/sites/{siteId}/ai-events:
    get:
      summary: Query AI events by site
      x-access-class: External
      parameters:
        - in: path
          name: siteId
          required: true
          schema:
            type: string
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
            maximum: 200
      responses:
        "200":
          description: Site scoped AI events
  /api/v1/sites/{siteId}/poll-state:
    get:
      summary: Query connector poll state by site
      x-access-class: External
      parameters:
        - in: path
          name: siteId
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Poll states
  /api/v1/sites/{siteId}/reports/anomalies:
    get:
      summary: Query anomalies by window
      x-access-class: External
      parameters:
        - $ref: "#/components/parameters/SiteId"
        - $ref: "#/components/parameters/Window"
      responses:
        "200":
          description: Anomaly list
  /api/v1/sites/{siteId}/reports/top-offline:
    get:
      summary: Top 20 offline cameras
      x-access-class: External
      parameters:
        - $ref: "#/components/parameters/SiteId"
        - $ref: "#/components/parameters/Window"
      responses:
        "200":
          description: Ranked cameras by offline count
  /api/v1/sites/{siteId}/reports/top-missing-recording:
    get:
      summary: Top 20 missing recording cameras
      x-access-class: External
      parameters:
        - $ref: "#/components/parameters/SiteId"
        - $ref: "#/components/parameters/Window"
      responses:
        "200":
          description: Ranked cameras by missing recording count
  /api/v1/sites/{siteId}/reports/accumulated-offline:
    get:
      summary: Rank by accumulated offline duration
      x-access-class: External
      parameters:
        - $ref: "#/components/parameters/SiteId"
        - $ref: "#/components/parameters/Window"
      responses:
        "200":
          description: Ranked accumulated offline duration
  /api/v1/sites/{siteId}/playback:
    get:
      summary: Playback query with index + fallback scan
      x-access-class: External
      parameters:
        - $ref: "#/components/parameters/SiteId"
        - in: query
          name: cameraId
          required: true
          schema:
            type: string
        - in: query
          name: start
          required: false
          schema:
            type: string
            format: date-time
        - in: query
          name: end
          required: false
          schema:
            type: string
            format: date-time
        - in: query
          name: page
          required: false
          schema:
            type: integer
            minimum: 0
        - in: query
          name: pageSize
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 50
      responses:
        "200":
          description: Playback response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PlaybackResponse"
        "400":
          description: Missing cameraId
        "503":
          description: Playback query unavailable
  /api/v1/sites/{siteId}/reports/management/overview:
    get:
      summary: Management KPI overview for decision support
      x-access-class: External
      parameters:
        - $ref: "#/components/parameters/SiteId"
        - $ref: "#/components/parameters/Window"
      responses:
        "200":
          description: Management KPI overview
  /api/v1/sites/{siteId}/reports/management/channel-performance:
    get:
      summary: Notification channel performance ranking
      x-access-class: External
      parameters:
        - $ref: "#/components/parameters/SiteId"
        - $ref: "#/components/parameters/Window"
      responses:
        "200":
          description: Channel performance result
  /api/v1/sites/{siteId}/reports/management/risk-ranking:
    get:
      summary: Camera risk ranking by weighted severity
      x-access-class: External
      parameters:
        - $ref: "#/components/parameters/SiteId"
        - $ref: "#/components/parameters/Window"
      responses:
        "200":
          description: Risk ranking result
  /api/v1/sites/{siteId}/dashboard/summary:
    get:
      summary: Site dashboard summary
      x-access-class: External
      parameters:
        - $ref: "#/components/parameters/SiteId"
      responses:
        "200":
          description: Dashboard summary
  /api/v1/sites/{siteId}/time-sync/status:
    get:
      summary: Time sync status and effective current time
      x-access-class: External
      parameters:
        - $ref: "#/components/parameters/SiteId"
      responses:
        "200":
          description: Time sync status
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TimeSyncStatusResponse"
  /api/v1/sites/{siteId}/time-sync/manual:
    post:
      summary: Set or clear manual time mode
      x-access-class: External
      parameters:
        - $ref: "#/components/parameters/SiteId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TimeSyncManualRequest"
      responses:
        "200":
          description: Manual time accepted
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TimeSyncStatusResponse"
        "400":
          description: Invalid request payload
components:
  parameters:
    SiteId:
      in: path
      name: siteId
      required: true
      schema:
        type: string
    Window:
      in: query
      name: window
      required: false
      schema:
        type: string
        enum: [15m, 1h, 4h, 8h, 24h]
  schemas:
    AiEvent:
      type: object
      required: [siteId, cameraId, eventType, severity, score, tsEvent, dedupKey]
      properties:
        siteId:
          type: string
        cameraId:
          type: string
        eventType:
          type: string
        severity:
          type: string
          enum: [normal, suspect, critical]
        score:
          type: number
          minimum: 0
          maximum: 1
        tsEvent:
          type: string
          format: date-time
        dedupKey:
          type: string
        metadata:
          type: object
          additionalProperties: true
    TimeSyncManualRequest:
      type: object
      additionalProperties: false
      properties:
        isoTime:
          oneOf:
            - type: string
              format: date-time
            - type: "null"
    TimeSyncStatusResponse:
      type: object
      required: [status, service, now, ntp]
      properties:
        status:
          type: string
          enum: [ok]
        service:
          type: string
        now:
          type: string
          format: date-time
        ntp:
          $ref: "#/components/schemas/NtpStatus"
    NtpStatus:
      type: object
      required:
        - enabled
        - mode
        - siteId
        - upstreamHost
        - upstreamPort
        - syncIntervalMin
        - requestTimeoutMs
        - serverEnabled
        - serverHost
        - serverPort
        - serverBound
        - offsetMs
      properties:
        enabled:
          type: boolean
        mode:
          type: string
          enum: [disabled, system, manual, upstream]
        siteId:
          type: string
        upstreamHost:
          type: string
        upstreamPort:
          type: integer
          minimum: 1
          maximum: 65535
        syncIntervalMin:
          type: integer
          minimum: 1
          maximum: 9999
        requestTimeoutMs:
          type: integer
          minimum: 100
        serverEnabled:
          type: boolean
        serverHost:
          type: string
        serverPort:
          type: integer
          minimum: 1
          maximum: 65535
        serverBound:
          type: boolean
        offsetMs:
          type: integer
        manualTimeIso:
          type: string
          format: date-time
        lastSyncAt:
          type: string
          format: date-time
        lastSuccessAt:
          type: string
          format: date-time
        lastError:
          type: string
    PlaybackRecord:
      type: object
      required: [ts, file, durationSec]
      properties:
        ts:
          type: string
          format: date-time
        file:
          type: string
        durationSec:
          type: integer
    PlaybackResponse:
      type: object
      required: [siteId, cameraId, source, items]
      properties:
        siteId:
          type: string
        cameraId:
          type: string
        source:
          type: string
          enum: [index, fallback]
        items:
          type: array
          items:
            $ref: "#/components/schemas/PlaybackRecord"
        nextPage:
          type: integer
          minimum: 0
        total:
          type: integer
          minimum: 0
        windowApplied:
          type: object
          required: [start, end]
          properties:
            start:
              type: string
              format: date-time
            end:
              type: string
              format: date-time
        pageSizeApplied:
          type: integer
          minimum: 1
          maximum: 50
        slowQueryMs:
          type: integer
          minimum: 0
        cacheHit:
          type: boolean
