name: Bug Report
description: Report a defect in VMM services, UI, or deployment
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Please provide exact reproduction details and logs.

  - type: input
    id: summary
    attributes:
      label: Summary
      placeholder: Brief bug summary
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Affected Area
      options:
        - connector-vss
        - ai-orchestrator
        - ai-worker
        - notification-gateway
        - reporting-engine
        - scheduler
        - web-dashboard
        - shared
        - infra/compose
        - docs
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Reproduction Steps
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      description: Paste relevant logs or screenshots

  - type: input
    id: environment
    attributes:
      label: Environment
      placeholder: local / staging / production
    validations:
      required: true